<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="lidar_radius" value="0.1" />
    <xacro:property name="lidar_length" value="0.12" />
    

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <origin xyz="0 0 ${lidar_length / 2}" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
        </collision>
       <xacro:cylinder_inertia m="0.8" r="${2*lidar_radius}" h="${2*lidar_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin xyz="0 0 ${base_height}" rpy="0 0 0" />
    </joint>
</robot>